FROM node:12.16.1-slim
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y build-essential git-core python
RUN npm install -g pm2
RUN npm install -g https://github.com/matuszeman/bb-box.git#2c16c3a9



